services:
  yamada-bot:
    container_name: yamada_ryo_bot
    build: .
    restart: always
    
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OWNER_ID=${OWNER_ID}

    volumes:
      - ${PATH}/db:/app/db
      - ${PATH}/logs:/app/logs
      - ${PATH}/data:/app/data
      
      # Persist yt-dlp cache so it doesn't re-download headers every restart
      - ${PATH}/data/cache:/.cache/yt-dlp