services:
  yamada-bot:
    container_name: yamada_ryo_bot
    image: tokachun/ymd-ryo:latest
    restart: always

    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
    volumes:
      - ${NAS_PATH}/db:/app/db
      - ${NAS_PATH}/logs:/app/logs
      - ${NAS_PATH}/data:/app/data
      - ${NAS_PATH}/data/cache:/.cache/yt-dlp
      - ${NAS_PATH}/.env:/app/.env

  watchtower:
    image: containrrr/watchtower
    container_name: ymd_bot_watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
    command: --interval 300 --label-enable