services:
  yamada-bot:
    image: tokachun/ymd-bot:latest

    restart: always
    env_file:
      - ${NAS_PATH}/.env
    volumes:
      - ${NAS_PATH}/db:/app/db
      - ${NAS_PATH}/logs:/app/logs
      - ${NAS_PATH}/data:/app/data
      - ${NAS_PATH}/data/cache:/.cache/yt-dlp
      - ${NAS_PATH}/.env:/app/.env